import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Porotfolio Amirulwicaksono",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png", // Menambahkan favicon
    shortcut: "/icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Favicon */}
        <link rel="icon" href="/icon.png" type="image/x-icon" />
      </head>
      <body className={`bg-white text-black dark:bg-gray-950 dark:text-white`}>
         <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
