import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Porotfolio Amirulwicaksono",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png", // Menambahkan favicon
    shortcut: "/icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <script defer src="https://cloud.umami.is/script.js" 
      data-website-id="1ee56d57-f696-4866-ace2-063051816cf4"></script>
        {/* Favicon */}
        <link rel="icon" href="/icon.png" type="image/x-icon" />
      </head>
      <body className={`bg-gray-100 text-black dark:bg-neutral-800 dark:text-white`}>
         <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
